#!/usr/bin/env python3
"""Emit the submission-safe subset of an IP's DV binds.

Upstream `<ip>_bind.sv` mixes three kinds of bind:

  * `tlul_assert` and `<ip>_csr_assert_fpv` connect only to the IP top's own
    ports (`clk_i`, `rst_ni`, `tl_i`, `tl_o`), so they attach to any
    implementation of the contract -- including a Verilog-2001 one whose `tl_i`
    is a plain vector.
  * coverage collectors such as `i2c_protocol_cov` reach in with hard paths like
    `$root.tb.dut.i2c_core.reg2hw...`, which name the reference's internals.
  * the `sec_cm_*_bind` modules target OpenTitan's countermeasure primitives,
    which a submission need not instantiate; VCS refuses a bind whose target is
    not elaborated.

Only the first kind can be elaborated against a submission, and it is elaborated
against the reference too, so the graded set is derived and applied under
identical conditions.

usage: mkbind.py <ip> > <ip>_bind_portlevel.sv
"""
import sys

ip = sys.argv[1]
print(f"""// GENERATED by ot-harness/mkbind.py -- port-level binds only.
module {ip}_bind_portlevel;

  bind {ip} tlul_assert #(
    .EndpointType("Device")
  ) tlul_assert_device (
    .clk_i,
    .rst_ni,
    .h2d  (tl_i),
    .d2h  (tl_o)
  );

  bind {ip} {ip}_csr_assert_fpv {ip}_csr_assert (
    .clk_i,
    .rst_ni,
    .h2d  (tl_i),
    .d2h  (tl_o)
  );

endmodule""")
