#!/usr/bin/env python3
"""Rename an IP top's register-file instance, leaving everything else identical.

This is the substitution filter: the result is functionally the same design, so
any test whose verdict changes is reading the reference's internal structure
rather than its interface, and cannot grade a submission.

usage: mkrenamed.py <ip_top.sv> > renamed.sv
"""
import re, sys

t = open(sys.argv[1]).read()
n = 0
# The instance line is either `<ip>_reg_top u_reg (` or, when the module takes
# parameters, `) u_reg (` closing the parameter list.
t, k = re.subn(r"^(\s*(?:\S+_reg_top|\))\s*)u_reg(\s*\()", r"\1u_regs\2", t, flags=re.M)
n += k
# ...and any macro that names the instance as a bare argument, e.g.
# `ASSERT_PRIM_REG_WE_ONEHOT_ERROR_TRIGGER_ALERT(RegWeOnehotCheck_A, u_reg, ...)`.
t, k = re.subn(r"(,\s*)u_reg(\s*,)", r"\1u_regs\2", t)
n += k
if re.search(r"\bu_reg\b", t):
    sys.exit("`u_reg` still referenced after renaming -- the result would not compile")
if n == 0:
    sys.exit("no `u_reg` register-file instance found in %s" % sys.argv[1])
print("// GENERATED by ot-harness/mkrenamed.py -- %d rename(s), no other change." % n)
sys.stdout.write(t)
