#!/usr/bin/env python3
"""Generate the negative control: `<ip>` that implements nothing.

Contract-compatible with a submission -- same module name, same struct port list,
and it brings its own `<ip>_reg_pkg` the way a submission does -- so the control
exercises the same path. It answers TL-UL (accept every request, return zero) and
drives every other output to a safe default. Every graded test must fail against
it; the register file is deliberately absent, so the CSR tests fail too.

usage: mkstub.py <ip> > <ip>_stub.sv          (OT_ROOT from the environment)
"""
import hjson, os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from otports import header

OT = os.environ["OT_ROOT"]

def reg_pkg(ip):
    """The parameters the DV env reads out of <ip>_reg_pkg, from the hjson."""
    cfg = hjson.load(open(f"{OT}/hw/ip/{ip}/data/{ip}.hjson"))
    out = [f"package {ip}_reg_pkg;"]
    for p in cfg.get("param_list") or []:
        if p.get("type") in (None, "int", "int unsigned"):
            out.append("  parameter int %s = %s;" % (p["name"], p["default"]))
    out.append("  parameter int NumAlerts = %d;" % len(cfg.get("alert_list") or []))
    out.append("  parameter int NumRegs = 1;")
    out.append("endpackage")
    return "\n".join(out)

def main():
    ip = sys.argv[1]
    imports, ports = header(f"{OT}/hw/ip/{ip}/rtl/{ip}.sv", ip)

    print("// GENERATED by ot-harness/mkstub.py -- negative control.")
    print("// Contract-compatible with a submission, implements nothing.")
    print(reg_pkg(ip))
    print()
    print("module %s" % ip)
    for i in imports:
        print("  " + i)
    print("(")
    print(",\n".join("  %-6s %s %s%s" % (d, t or "logic", n, (" " + x) if x else "")
                     for d, t, n, x in ports))
    print(");")
    print("""
  // Minimal TL-UL device: accept one request at a time, answer with zero data.
  logic               pend_q;
  tlul_pkg::tl_a_op_e op_q;
  logic [7:0]         src_q;
  logic [2:0]         size_q;

  always_ff @(posedge clk_i or negedge rst_ni) begin
    if (!rst_ni) begin
      pend_q <= 1'b0;
    end else if (tl_i.a_valid && !pend_q) begin
      pend_q <= 1'b1;
      op_q   <= tl_i.a_opcode;
      src_q  <= tl_i.a_source;
      size_q <= tl_i.a_size;
    end else if (pend_q && tl_i.d_ready) begin
      pend_q <= 1'b0;
    end
  end

  always_comb begin
    tl_o          = tlul_pkg::TL_D2H_DEFAULT;
    tl_o.a_ready  = !pend_q;
    tl_o.d_valid  = pend_q;
    tl_o.d_opcode = (op_q == tlul_pkg::Get) ? tlul_pkg::AccessAckData
                                            : tlul_pkg::AccessAck;
    tl_o.d_size   = size_q;
    tl_o.d_source = src_q;
    tl_o.d_data   = '0;
  end""")
    for d, t, n, x in ports:
        if d != "output" or n == "tl_o":
            continue
        val = ("'{default: prim_alert_pkg::ALERT_TX_DEFAULT}"
               if "alert_tx" in n else "'0")
        print("  assign %s = %s;" % (n, val))
    print("endmodule")

main()
