#!/usr/bin/env python3
"""Derive an eval/scoreable.txt from run.sh outputs.

A test grades a submission only if it satisfies all three:

  1. PASS on the reference RTL, on every seed swept. A test that fails on the
     design the environment was written for cannot grade anything, and one that is
     flaky on the reference would fail a correct submission at random.
  2. Same verdict on a copy of the reference whose register-file instance has been
     renamed. A verdict that moves is reading the reference's internal structure,
     not its interface.
  3. FAIL on the generated stub. Without this the other two prove nothing.

usage:
  scoreable.py --ref ref.s1 [--ref ref.s2 ...] --renamed ren.s1 --stub stub.s1
               --out scoreable.txt [--report]
"""
import argparse, sys

def read(path):
    out = {}
    for line in open(path):
        parts = line.split()
        if len(parts) >= 2 and not line.startswith("#"):
            out[parts[0]] = parts[1]
    return out

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--ref", action="append", required=True)
    ap.add_argument("--renamed", required=True)
    ap.add_argument("--stub", required=True)
    ap.add_argument("--out", required=True)
    ap.add_argument("--report", action="store_true")
    a = ap.parse_args()

    refs = [read(p) for p in a.ref]
    ren, stub = read(a.renamed), read(a.stub)
    names = sorted(refs[0])

    keep, drop = [], []
    for n in names:
        rv = [r.get(n, "MISSING") for r in refs]
        if any(v != "PASS" for v in rv):
            drop.append((n, "reference " + "/".join(rv)))
        elif ren.get(n) != "PASS":
            drop.append((n, "verdict moves under rename: " + str(ren.get(n))))
        elif not str(stub.get(n, "")).startswith("FAIL"):
            drop.append((n, "stub does not fail it: " + str(stub.get(n))))
        else:
            keep.append(n)

    body = ["# GENERATED by ot-harness/scoreable.py -- see the task README for the criteria.",
            "# %d of %d tests grade a submission." % (len(keep), len(names))] + keep
    open(a.out, "w").write("\n".join(body) + "\n")
    print("wrote %s: %d scoreable, %d excluded" % (a.out, len(keep), len(drop)))
    if a.report:
        print("\n# excluded", file=sys.stderr)
        for n, why in drop:
            print("%-44s %s" % (n, why), file=sys.stderr)

main()
